version: '3.8'
services:
  web:
    build: .
    ports:
      - "6060:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
