apiVersion: v2
name: yesnoapp
description: A Helm chart for Yes-No Flask App
version: 0.1.0

dependencies:
  - name: redis
    version: "18.12.1" # Specify the version of the Redis chart you wish to use
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
