apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yesnoapp.fullname" . }}
  labels:
    {{- include "yesnoapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "yesnoapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "yesnoapp.labels" . | nindent 8 }}
    spec:
      containers:
        - name: yesnoapp
          image: "{{ .Values.yesnoapp.image.repository }}:{{ .Values.yesnoapp.image.tag }}"
          imagePullPolicy: {{ .Values.yesnoapp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.yesnoapp.service.targetPort }}
          envFrom:
          - configMapRef:
              name: {{ include "yesnoapp.fullname" . }}-envs
